### PR TITLE
Added localization, user configuration and CSS minification

### PR DESCRIPTION
**Pull request by mike182uk**
## Features Added
- **Localization (L10n) Support** - When i first started using this app i noticed the months where in german. Rather than simply replacing them to english equivalents i have added L10n.json which contains localized data depending on the users preference. This could be expanded to include lots of other locales.
- **User Configuration Support** - For the localization support to work correctly the user needs the ability to select there locale. I have created a configuration page the user can go to, to modify the configuration of the app. I have moved the show love message here as-well. I think on the homescreen rather than having the 'show love' icon in the bottom bar, a cog icon (indicates settings) would be more appropriate which would then take you to the conifg page (where you can modify multiple settings for the app). This adds scope to add more configurable options later.
- **CSS Minification Support** - On the configuration page the user can select wether they want the CSS output to be minified or not.
## Notes

**Design**

Unfortunately im not a designer so im not too good at making things look pretty :( You did an awesome job with the looks of the app so i have left the design of the configure cog, and configuration page up to you.

**Misc**

I have used localStorage to save the users configuration data. Im not 100% sure how titanium works with this but when i was testing it seemed to work fine with me (making changes, rebooting app etc.)

The users configuration data is saved as a JSON string (stringified). It needs parsing on retrieval.

The CSS minification is done by a series of regular expressions. I have tested on a few different less files (with different levels of formattings) and it seems to work fine. Regular expressions could probably do with refactoring a little though.

### CODE REVIEW

**Comment by Paratron** [comment]
Wow, thanks for your work :)

First away: the months werent in german - I simply had typos in may and october... wasn't paying attention there :/
But as mentioned in [issue 5](https://github.com/Paratron/SimpLESS/issues/5) that was a typo and is fixed with version 1.2

I did some major changes for 1.2 which arent commited jet - so I wait with pulling your changes until after the release of 1.2

**Comment by mike182uk** [comment]
ah i see, well on the version i forked may = mai, and october = okt and there looked like there where some german comments, so i assumed it was german :) Anyhow, localization isn't such a bad idea.

ah rite cool, hope i aint wasted my time working on features you have already developed... ;-)

really like the app, i love less.app but like how simpLESS is open source and works across different OS ( i have mac at home, but use windows at work ). There is alot of potential for this app :)

what is your ETA to push the 1.2 changes?

**Comment by Paratron** [comment]
Yeah, there was one german comment left over, too :D

Nope, localization and minification isn't built in right now. I think there will be some problems with i16n, tough - since some parts of the app are images. This is the "Drag & Drop" image on startup and the popup-box of the show-love option.
The last one will be deprecated when adding a settings sheet, which will be required when adding more functionality to SimpLESS like minification, auto-prefixing and other stuff that is in pipe.

By the way, 1.2 will bring the following changes:
- implemented a new drag&drop system. Should work much more reliable now.
- fixed a bug where a space in the filepath prevented simpless from recognizing it.
- fixed a bug where the "show love" message was displayed when it shouldnt
- improved compilation error checking
- improved contrast in the colors of error messages in the UI
- included LESS parser 1.1.4
- added @import functionality
- when minimizing the app, it goes to the tray
- added a "restore last session" button

**Comment by Paratron** [comment]
Oh and I think I can publish the update somewhen on monday. I am currently testing 1.2 under osX and Linux

**Comment by raulriera** [comment]
Would love to see this pull merged

**Comment by Paratron** [comment]
Minification (based on YUIs principle) is implemented with a previous commit - multilanguage wont be implemented to keep the app small.

**Pull request closed without merging**
