### PR TITLE
Visual tweak, TypeError preventing and Linux love

### PR DESCRIPTION
**Pull request by MrMitch**

### CODE REVIEW

**Comment by MrMitch** [comment]
is anyone still in charge of this repository ?

**Comment by wyqydsyq** [comment]
It looks quite abandoned, would be nice if @Paratron added someone else as a maintainer.

**Comment by krismeister** [comment]
I've been helping out just recently. I'm not very familiar with linux, so i can't test these easily.

Also a big change since this pull request, was switching to TideSDK, which is the new name of Titanium.  Pretty much the most critical remaining bugs to complete simpLESS 1.5 rely on LESS 1.4 getting released.

I'll leave this request open for now. Later.

**Comment by Paratron** [comment]
The upgrade to TideSDK _should_ fix the linux problems. I will pull the repo and check it on my linux box later.

**Comment by Paratron** [comment]
Does not apply anymore for branch 2.0

**Pull request closed without merging**
